# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ap576391/Documents/Hermann/Fibo_vivado/Fibo_vivado.srcs/sources_1/bd/systeme/ip/systeme_fibonacci_0_0/systeme_fibonacci_0_0.xci
# IP: The module: 'systeme_fibonacci_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ap576391/Documents/Hermann/Fibo_vivado/Fibo_vivado.srcs/sources_1/bd/systeme/ip/systeme_fibonacci_0_0/constraints/fibonacci_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'systeme_fibonacci_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ap576391/Documents/Hermann/Fibo_vivado/Fibo_vivado.srcs/sources_1/bd/systeme/ip/systeme_fibonacci_0_0/systeme_fibonacci_0_0.xci
# IP: The module: 'systeme_fibonacci_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ap576391/Documents/Hermann/Fibo_vivado/Fibo_vivado.srcs/sources_1/bd/systeme/ip/systeme_fibonacci_0_0/constraints/fibonacci_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'systeme_fibonacci_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
