// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fibonacci.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fibonacci::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fibonacci::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> fibonacci::ap_ST_fsm_state1 = "1";
const sc_lv<2> fibonacci::ap_ST_fsm_state2 = "10";
const int fibonacci::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> fibonacci::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fibonacci::ap_const_lv32_1 = "1";
const sc_lv<1> fibonacci::ap_const_lv1_0 = "0";
const sc_lv<32> fibonacci::ap_const_lv32_2 = "10";
const sc_lv<1> fibonacci::ap_const_lv1_1 = "1";
const bool fibonacci::ap_const_boolean_1 = true;

fibonacci::fibonacci(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fibonacci_AXILiteS_s_axi_U = new fibonacci_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("fibonacci_AXILiteS_s_axi_U");
    fibonacci_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    fibonacci_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    fibonacci_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    fibonacci_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    fibonacci_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    fibonacci_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    fibonacci_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    fibonacci_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    fibonacci_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    fibonacci_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    fibonacci_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    fibonacci_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    fibonacci_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    fibonacci_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    fibonacci_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    fibonacci_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    fibonacci_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    fibonacci_AXILiteS_s_axi_U->ACLK(ap_clk);
    fibonacci_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    fibonacci_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    fibonacci_AXILiteS_s_axi_U->entre(entre);
    fibonacci_AXILiteS_s_axi_U->sortie(ap_phi_mux_storemerge_phi_fu_91_p4);
    fibonacci_AXILiteS_s_axi_U->sortie_ap_vld(sortie_ap_vld);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_fu_111_p2);
    sensitive << ( F0_reg_41 );
    sensitive << ( F0_0_reg_53 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_phi_mux_storemerge_phi_fu_91_p4);
    sensitive << ( icmp_ln14_reg_128 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_106_p2 );
    sensitive << ( F2_0_reg_65 );
    sensitive << ( storemerge_reg_87 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_i_fu_117_p2);
    sensitive << ( i_0_reg_76 );

    SC_METHOD(thread_icmp_ln14_fu_100_p2);
    sensitive << ( entre );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_icmp_ln16_fu_106_p2);
    sensitive << ( entre_read_reg_123 );
    sensitive << ( icmp_ln14_reg_128 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_76 );

    SC_METHOD(thread_sortie_ap_vld);
    sensitive << ( icmp_ln14_reg_128 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_106_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( icmp_ln14_reg_128 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_106_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fibonacci_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, entre, "entre");
    sc_trace(mVcdFile, sortie_ap_vld, "sortie_ap_vld");
    sc_trace(mVcdFile, entre_read_reg_123, "entre_read_reg_123");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, icmp_ln14_fu_100_p2, "icmp_ln14_fu_100_p2");
    sc_trace(mVcdFile, icmp_ln14_reg_128, "icmp_ln14_reg_128");
    sc_trace(mVcdFile, F2_fu_111_p2, "F2_fu_111_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln16_fu_106_p2, "icmp_ln16_fu_106_p2");
    sc_trace(mVcdFile, i_fu_117_p2, "i_fu_117_p2");
    sc_trace(mVcdFile, F0_reg_41, "F0_reg_41");
    sc_trace(mVcdFile, F0_0_reg_53, "F0_0_reg_53");
    sc_trace(mVcdFile, F2_0_reg_65, "F2_0_reg_65");
    sc_trace(mVcdFile, i_0_reg_76, "i_0_reg_76");
    sc_trace(mVcdFile, ap_phi_mux_storemerge_phi_fu_91_p4, "ap_phi_mux_storemerge_phi_fu_91_p4");
    sc_trace(mVcdFile, storemerge_reg_87, "storemerge_reg_87");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("fibonacci.hdltvin.dat");
    mHdltvoutHandle.open("fibonacci.hdltvout.dat");
}

fibonacci::~fibonacci() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete fibonacci_AXILiteS_s_axi_U;
}

void fibonacci::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void fibonacci::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_100_p2.read(), ap_const_lv1_0))) {
        F0_0_reg_53 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln16_fu_106_p2.read()))) {
        F0_0_reg_53 = F0_reg_41.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_100_p2.read(), ap_const_lv1_0))) {
        F0_reg_41 = ap_const_lv32_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln16_fu_106_p2.read()))) {
        F0_reg_41 = F2_fu_111_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_100_p2.read(), ap_const_lv1_0))) {
        F2_0_reg_65 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln16_fu_106_p2.read()))) {
        F2_0_reg_65 = F2_fu_111_p2.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_100_p2.read(), ap_const_lv1_0))) {
        i_0_reg_76 = ap_const_lv32_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln16_fu_106_p2.read()))) {
        i_0_reg_76 = i_fu_117_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_106_p2.read(), ap_const_lv1_1))) {
        storemerge_reg_87 = F2_0_reg_65.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(icmp_ln14_fu_100_p2.read(), ap_const_lv1_1))) {
        storemerge_reg_87 = ap_const_lv32_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        entre_read_reg_123 = entre.read();
        icmp_ln14_reg_128 = icmp_ln14_fu_100_p2.read();
    }
}

void fibonacci::thread_F2_fu_111_p2() {
    F2_fu_111_p2 = (!F0_0_reg_53.read().is_01() || !F0_reg_41.read().is_01())? sc_lv<32>(): (sc_biguint<32>(F0_0_reg_53.read()) + sc_biguint<32>(F0_reg_41.read()));
}

void fibonacci::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fibonacci::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fibonacci::thread_ap_phi_mux_storemerge_phi_fu_91_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_106_p2.read(), ap_const_lv1_1))) {
        ap_phi_mux_storemerge_phi_fu_91_p4 = F2_0_reg_65.read();
    } else {
        ap_phi_mux_storemerge_phi_fu_91_p4 = storemerge_reg_87.read();
    }
}

void fibonacci::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void fibonacci::thread_i_fu_117_p2() {
    i_fu_117_p2 = (!i_0_reg_76.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_0_reg_76.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void fibonacci::thread_icmp_ln14_fu_100_p2() {
    icmp_ln14_fu_100_p2 = (!entre.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<1>(): sc_lv<1>(entre.read() == ap_const_lv32_1);
}

void fibonacci::thread_icmp_ln16_fu_106_p2() {
    icmp_ln16_fu_106_p2 = (!i_0_reg_76.read().is_01() || !entre_read_reg_123.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_0_reg_76.read()) > sc_bigint<32>(entre_read_reg_123.read()));
}

void fibonacci::thread_sortie_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         (esl_seteq<1,1,1>(icmp_ln16_fu_106_p2.read(), ap_const_lv1_1) || 
          esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_1)))) {
        sortie_ap_vld = ap_const_logic_1;
    } else {
        sortie_ap_vld = ap_const_logic_0;
    }
}

void fibonacci::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && (esl_seteq<1,1,1>(icmp_ln16_fu_106_p2.read(), ap_const_lv1_1) || 
  esl_seteq<1,1,1>(icmp_ln14_reg_128.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void fibonacci::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

